### ISSUE TITLE
Int-Values for post-data in http-client not possible

### ISSUE THREAD

**Issue by whotwagner** [ait-testbed/attackmate#146]
The following command does not work:

```yaml
commands:
  # Scanning wordpress instance ...
  - type: http-client
    cmd: POST
    url: http://192.168.0.78:8888/target_power
    data:
       target_power_command: 4000
```

One has to put quotes around 4000. But then, the json-string for the post-data is not correct anymore. it should look like:

```json
{"target_power_command": 4000}
```

instead of:

```json
 {"target_power_command": "4000"}
```
