### ISSUE TITLE
Add Ability to Pause Playbook Execution

### ISSUE THREAD

**Issue by git-lreuter** [ait-testbed/attackmate#147]
It should be possible to pause the execution of a playbook and wait for manual input from the user before continuing. This functionality could be implemented as an additional flag or option in the `debug` command.

e.g.:
```yaml
 - type: debug
    cmd: 'Playbook paused. Press [ENTER] to continue.'
    pause: True
```
