### ISSUE TITLE
Support for local interactive command

### ISSUE THREAD

**Issue by Seb1n1h0** [ait-testbed/attackmate#65]
Hi,
I want to execute Evil-WinRM and as of now, the attmate has no prompt / integration of it.

**Comment by whotwagner** [comment]
shell-commands do now support the interactive-mode

```yaml
commands:
  - type: shell
    cmd: "evil-winrm -i 10.18.5.223 -u winuser -p winpw1! -r win.local -S -n -N\n"
    command_timeout: 20
    interactive: true
    creates_session: evil

  - type: shell
    session: evil
    command_timeout: 20
    cmd: "ls\n"
    interactive: true
```
