### ISSUE TITLE
Interactive ssh-commands in development-branch do not timeout correctly

### ISSUE THREAD

**Issue by whotwagner** [ait-testbed/attackmate#75]
When executing htop in an interactive session, it will block forever. 

```yaml
  - type: ssh
    cmd: "htop\n"
    session: $SESSION
    interactive: True
    command_timeout: 10


  - type: ssh
    cmd: "03"
    bin: true
    session: $SESSION
    interactive: True
```
